# .github/workflows/dependency-review.yml
name: Dependency Review

on:
  pull_request:
    branches: [ main, dev ]

jobs:
  dependency-review:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      pull-requests: write  # allow PR comments
    steps:
      - uses: actions/checkout@v4
      - uses: actions/dependency-review-action@v4
        with:
          fail-on-severity: high          # block PRs adding High/Critical vulns
          comment-summary-in-pr: true     # post a summary comment
          # Optional policy knobs:
          # allow-licenses: MIT,Apache-2.0
          # deny-licenses: GPL-3.0
          # allow-ghsas: GHSA-xxxx-xxxx-xxxx
          # warn-only: false