name: Deploy to Vercel
on:
  push:
    branches: [ main, dev ]
  workflow_dispatch:

env:
  VERCEL_ORG_ID: ${{ secrets.VERCEL_ORG_ID }}
  VERCEL_PROJECT_ID: ${{ secrets.VERCEL_PROJECT_ID }}
  VERCEL_TOKEN: ${{ secrets.VERCEL_TOKEN }}
  DEPLOY_ENV: ${{ github.ref == 'refs/heads/main' && 'production' || 'preview' }}
  PROD_FLAG: ${{ github.ref == 'refs/heads/main' && '--prod' || '' }}

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: npm
      - run: npm ci
      - run: npm i -g vercel@latest

      - name: Pull env
        run: vercel pull --yes --environment=$DEPLOY_ENV

      - name: Build
        run: vercel build $PROD_FLAG

      - name: Deploy
        run: |
          set -e
          URL=$(vercel deploy --prebuilt $PROD_FLAG | tail -n1)
          echo "Deployed: $URL"